### ISSUE TITLE
ci: move all CI steps from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by yskopets** [tetratelabs/getenvoy#100]

**Comment by codefromthecrypt** [comment]
Agree with this as the differences between CI aren't helpful.

**Comment by codefromthecrypt** [comment]
This is locked up due to some tests failing severely when executed in GH actions. Here's the snippet that ideally would have things work

```yaml
  check:
    name: "Run CI checks on Linux"
    runs-on: ubuntu-latest
    container: golang:1.16  # match go.mod version
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'

      - name: "Init on first use"
        run: make init

      - name: "Run checks"
        run: make check

  test:
    name: "Run unit tests on Linux"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'

      - name: "Init on first use"
        run: make init

      - name: "Prefetch latest envoy"
        run: go run cmd/getenvoy/main.go fetch standard:1.17.1

      - name: "Run tests"
        run: make test GO_TEST_EXTRA_OPTS="-timeout 60s -v"

      - name: "Generate coverage report"
        run: make coverage GO_COVERAGE_EXTRA_OPTS="-p 1"

      - name: "Upload coverage report"
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: build/coverage
```

the check task works, test runs a few until eventually they blow up like so:
```
ok  	github.com/tetratelabs/getenvoy/pkg/binary/envoy/controlplane	21.264s
go build github.com/tetratelabs/getenvoy/pkg/cmd.test: open /tmp/go-build1173000906/b1040/importcfg: no such file or directory
# github.com/russross/blackfriday
vet: in github.com/russross/blackfriday, can't import facts for package "bytes": open $WORK/b038/vet.out: no such file or directory
# github.com/cpuguy83/go-md2man/md2man
vet: in github.com/cpuguy83/go-md2man/md2man, can't import facts for package "bytes": open $WORK/b038/vet.out: no such file or directory
# github.com/spf13/cobra/doc
vet: in github.com/spf13/cobra/doc, can't import facts for package "bytes": open $WORK/b038/vet.out: no such file or directory
# github.com/tetratelabs/getenvoy/pkg/binary/envoy/controlplane
vet: in github.com/tetratelabs/getenvoy/pkg/binary/envoy/controlplane, can't import facts for package "errors": open $WORK/b003/vet.out: no such file or directory
# github.com/mattn/go-isatty
vet: in github.com/mattn/go-isatty, can't import facts for package "golang.org/x/sys/unix": open $WORK/b195/vet.out: no such file or directory
# github.com/opencontainers/go-digest
vet: in github.com/opencontainers/go-digest, can't import facts for package "crypto": open $WORK/b067/vet.out: no such file or directory
# github.com/docker/distribution/digestset
vet: in github.com/docker/distribution/digestset, can't import facts for package "errors": open $WORK/b003/vet.out: no such file or directory
# github.com/docker/distribution/reference
vet: in github.com/docker/distribution/reference, can't import facts for package "path": open $WORK/b036/vet.out: no such file or directory
# github.com/tetratelabs/getenvoy/pkg/extension/workspace/config
vet: in github.com/tetratelabs/getenvoy/pkg/extension/workspace/config, can't import facts for package "github.com/ghodss/yaml": open $WORK/b533/vet.out: no such file or directory
# github.com/tetratelabs/getenvoy/pkg/extension/workspace/config/toolchain/builtin
vet: in github.com/tetratelabs/getenvoy/pkg/extension/workspace/config/toolchain/builtin, can't import facts for package "path": open $WORK/b036/vet.out: no such file or directory
# github.com/tetratelabs/getenvoy/pkg/extension/workspace/config/example
vet: in github.com/tetratelabs/getenvoy/pkg/extension/workspace/config/example, can't import facts for package "github.com/pkg/errors": open $WORK/b049/vet.out: no such file or directory
# github.com/tetratelabs/getenvoy/pkg/extension/workspace/config/extension
vet: in github.com/tetratelabs/getenvoy/pkg/extension/workspace/config/extension, can't import facts for package "encoding/json": open $WORK/b039/vet.out: no such file or directory
# github.com/tetratelabs/getenvoy/pkg/util/os
vet: in github.com/tetratelabs/getenvoy/pkg/util/os, can't import facts for package "os": open $WORK/b030/vet.out: no such file or directory
# github.com/tetratelabs/getenvoy/pkg/extension/workspace/fs
vet: in github.com/tetratelabs/getenvoy/pkg/extension/workspace/fs, can't import facts for package "os": open $WORK/b030/vet.out: no such file or directory
# github.com/tetratelabs/getenvoy/pkg/extension/workspace/model
vet: in github.com/tetratelabs/getenvoy/pkg/extension/workspace/model, can't import facts for package "github.com/pkg/errors": open $WORK/b049/vet.out: no such file or directory
# github.com/tetratelabs/getenvoy/pkg/extension/workspace/toolchain/types
vet: in github.com/tetratelabs/getenvoy/pkg/extension/workspace/toolchain/types, can't import facts for package "github.com/tetratelabs/getenvoy/pkg/util/io": open $WORK/b183/vet.out: no such file or directory
```
