### ISSUE TITLE
regenerate site/install.sh after release

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/getenvoy#238]
We unfortunately overridded goreleaser naming conventions formerly like this:

```
archives:
  - name_template: "getenvoy_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
```

This is distracting and busy work especially as we add new platforms. We now release defaults (which naturally map to docker platform and our json schema).

After we release current master, we need to regenerate and push `site/install.sh` to catch the naming convention updates.
Ex. using latest commit of https://github.com/goreleaser/godownloader

```bash
./godownloader --repo=tetratelabs/getenvoy  .goreleaser.yaml  > site/install.sh 
```
