### ISSUE TITLE
Revert `getenvoy run` to excute envoy in the CWD

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/getenvoy#263]
Right now, `getenvoy run` executes envoy in a different directory (the "run" directory). This was a mistake in hindsight because it makes running envoy more difficult as the config file must be an absolute path.

Ex. this won't work
```
$ getenvoy run -c ./my-config.yml
```

This will
```bash
$ getenvoy run -c $PWD/my-config.yml
```

However, the $PWD trick won't work with included files, as those are resolved by envoy based on the cwd, not relative to the path of the config file.

Ex. relative paths like this:
```yaml
                          vm_config:
                            vm_id: "my_vm_id"
                            runtime: "envoy.wasm.runtime.v8"
                            code:
                              local:
                                filename: "./examples/http_body/main.go.wasm"
```

We need to change the behavior to execute in the current working directory and backfill an E2E test that proves file resolution relative to the config file works.
