### ISSUE TITLE
Upcoming envoy makes inlined config almost impossible

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/getenvoy#273]
right now, we use something simple like this to run tests.

```
envoy --config-yaml "admin: {access_log_path: '/dev/stdout', address: {socket_address: {address: '127.0.0.1', port_value: 0}}}"
```

We're forced to put the access_log_path in there though some reason windows doesn't require it (and if you supply /dev/stdout it will fail)

It seems this is replaced with a more elaborate and futile to inline alternative.  https://github.com/envoyproxy/envoy/pull/15461 I'm not sure if they allow opting out of access logs for admin cc @phlax 

```yaml
admin:
  access_log:
    - name: envoy.access_loggers.stdout
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
  address:
    socket_address:
      address: '127.0.0.1'
      port_value: 0
```

In any case, it appears a one-liner to try envoy may no longer be possible, so we should update docs.
